# -*- coding: utf-8 -*-
"""fetch_wind.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13R_oQlRty83i0aiQl9U0XKwzE7d-SbBW
"""

import ee
ee.Authenticate()
ee.Initialize(project='canvas-radio-444702-k2')

import geemap
import datetime
import requests
import os
import xarray as xr

from herbie import Herbie

california = ee.FeatureCollection("TIGER/2018/States") \
            .filter(ee.Filter.eq("NAME", "California"))

# Get today's date in YYYYMMDD format
today = datetime.datetime.utcnow().strftime("%Y%m%d")

#Fetch the latest HRRR dataset
H = Herbie(
    date=today,   # Use today's date
    model="hrrr",
    product="sfc", # model product
    fxx=0  # Forecast hour (0 = analysis time)
)

# Download the full HRRR file
H.download()
subset = H.download(":U10|V10:GRD:10 m above", verbose=True) #subset contains 10m standard height

ds = H.xarray(r":[U|V]GRD:10 m above")
print (ds)

#define output file name
output_file = f"RT_wind_{today}.nc"
#save as NetCDF
ds.to_netcdf(output_file)
print(f"NetCDF file saved as {output_file}")

from google.cloud import storage
# save in GCS
def upload_to_gcs(bucket_name, source_file_name, destination_blob_name):
    storage_client = storage.Client()
    bucket = storage_client.bucket(bucket_name)
    blob = bucket.blob(destination_blob_name)

    blob.upload_from_filename(source_file_name)
    print(f" Uploaded {source_file_name} to gs://{bucket_name}/{destination_blob_name}")

# Set bucket name
BUCKET_NAME = "wildfire-monitor-data"

# Upload file
upload_to_gcs(BUCKET_NAME, output_file, output_file)



















